export function getNextSiblings(el: any, filter?: string): any[];
export function getPreviousSiblings(el: any, filter?: string): any[];
export function getAllSiblings(el: any, filter?: string): any[];
export function getParents(el: any, filter?: string): any[];
export function getChildren(el: any, filter?: string, all?: any[]): any[];
export function isRootElement(element: any): any;
export function getDocument(node: any): any;
export function isNode(value: any): boolean;
export function isElement(value: any): boolean;
export function isHTMLElement(value: any): boolean;
export function isShadowRoot(value: any): boolean;
export function nodeContains(parent: any, child: any): boolean;
